version: "3"
services:
  node:
    container_name: node
    build: 
      context: ./node
      target: ${TARGET}
    links:
      - redis
    ports:
      - "127.0.0.1:3000:3000"
    volumes: 
      - ./node/src:/usr/src/app/src
    tty: true
    environment: 
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PORT=3000

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  nginx-proxy:
    extends:
        file: ./config/docker.${FILE_EXT}.yml
        service: nginx-proxy
    image: nginx
    container_name: nginx-proxy
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - conf:/etc/nginx/conf.d
        - html:/usr/share/nginx/html
        - ./nginx/error.html:/var/www/default/error.html:ro
        - ./nginx/favicon.png:/var/www/default/favicon.png:ro
        - ./nginx/vhost.d:/etc/nginx/vhost.d
        - ./nginx/conf.d/server.conf:/etc/nginx/conf.d/server.conf:ro
        - ./nginx/include:/etc/nginx/include:ro
    restart: always
  
  docker-gen:
      extends:
          file: ./config/docker.${FILE_EXT}.yml
          service: docker-gen
      image: jwilder/docker-gen
      command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
      container_name: nginx-proxy-gen
      depends_on:
          - nginx-proxy
      volumes:
          - conf:/etc/nginx/conf.d
          - ./nginx/vhost.d:/etc/nginx/vhost.d
          - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
          - /var/run/docker.sock:/tmp/docker.sock:ro
      restart: always

  letsencrypt:
      image: nginxproxy/acme-companion
      container_name: nginx-proxy-le
      depends_on:
          - nginx-proxy
          - docker-gen
      volumes:
          - vhost:/etc/nginx/vhost.d
          - html:/usr/share/nginx/html
          - certs:/etc/nginx/certs
          - conf:/etc/nginx/conf.d
          - acme:/etc/acme.sh
          - /var/run/docker.sock:/var/run/docker.sock:ro
      environment:
          - NGINX_PROXY_CONTAINER=nginx-proxy
          - NGINX_DOCKER_GEN_CONTAINER=nginx-proxy-gen
          - DEFAULT_EMAIL=ssl@tankmayhem.com
      restart: always

volumes:
  conf:
  vhost: 
  html:
  certs:
  acme:

networks:
  default:
      name: nginx-proxy