services:
  nginx-proxy:
    volumes:
      - ../nginx/certs:/etc/nginx/certs:ro
  docker-gen:
    volumes:
      - ../nginx/certs:/etc/nginx/certs:ro
  api:
    volumes:
      - ../nginx/certs:/etc/nginx/certs:ro