services:
  nginx-proxy:
    volumes:
      - ../nginx/certs:/etc/nginx/certs:ro
  docker-gen:
    volumes:
      - ../nginx/certs:/etc/nginx/certs:ro
  node:
    volumes:
      - ../nginx/certs:/etc/nginx/certs:ro
      - ../node/public:/usr/src/app/public:ro
      - ../node/src:/usr/src/app/src:ro